#include "under_test.h"

int main()
{
	//Test_ECIES_1::Test_ECIES_encrypt1();
	//Test_ECIES_1::Test_ECIES_encrypt2();

	//Test_ECIES_2::Run_Test_ECIES_2();


	//INTEROP_TEST_ECIES::test1();
	//INTEROP_TEST_ECIES::test2();
	//INTEROP_TEST_ECIES::test3();
	//INTEROP_TEST_ECIES::test4();
	//INTEROP_TEST_ECIES::test5();
	//INTEROP_TEST_ECIES::test6();

	//INTEROP_TEST_ECDSA::test1();
	//INTEROP_TEST_ECDSA::test2();
	//INTEROP_TEST_ECDSA::test3();
	//INTEROP_TEST_ECDSA::test4();
	//INTEROP_TEST_ECDSA::test5();


	//INTEROP_TEST_DH::test1();
	//INTEROP_TEST_DH::test2();
	//INTEROP_TEST_DH::test3();
	//INTEROP_TEST_DH::test4();

	//INTEROP_TEST_SYMMETRICCRYPT::test1();
	//INTEROP_TEST_SYMMETRICCRYPT::test2();
	//INTEROP_TEST_SYMMETRICCRYPT::test3();
	//INTEROP_TEST_SYMMETRICCRYPT::test4();
	//INTEROP_TEST_SYMMETRICCRYPT::test5();
	//INTEROP_TEST_SYMMETRICCRYPT::test6();
	//INTEROP_TEST_SYMMETRICCRYPT::test7();
	//INTEROP_TEST_SYMMETRICCRYPT::test11();

	AUX_TEST::test1();
	AUX_TEST::test2();
}
